### ISSUE TITLE
Organizer *folk(s) waiting* metric should be seed from the socket and not calculated as 0 every time

### ISSUE THREAD

**Issue by uri** [ElixirOttawaMeetup/ring-my-bell-ex#8]
Should be pretty simple, will require something like 

```elixir
render :show, waiters_count: Channel.do_something
```

Not sure if you can get a channel's state outside of it's scope. The state of a channel might be better handled with a GenServer.

**Comment by maxneuvians** [comment]
Pulling this out of `RingMyBellEx.BellAgent.list_ringers`
